### ISSUE TITLE
perl 5.8.8 support

### ISSUE THREAD

**Issue by dsilva** [CindyLinz/Perl-DestructAssign#1]
Hi,

Looks like this isn't building under perl 5.8.8:
http://matrix.cpantesters.org/?dist=DestructAssign%200.002003;os=linux;perl=5.8.8;reports=1
     Error:  Can't load '/home/njh/.cpan/build/DestructAssign-0.002003-AcLddZ/blib/arch/auto/DestructAssign/DestructAssign.so' for module DestructAssign: /home/njh/.cpan/build/DestructAssign-0.002003-AcLddZ/blib/arch/auto/DestructAssign/DestructAssign.so: undefined symbol: find_runcv at /home/njh/perl5/perlbrew/perls/perl-5.8.8/lib/5.8.8/x86_64-linux-thread-multi/DynaLoader.pm line 230.

The macro find_runcv wasn't available in 5.8.8 and the function it pointed to, Perl_find_runcv, was also not part of the pubic API.  This is referenced in a similar issue in Devel-Optrace:
https://rt.cpan.org/Public/Bug/Display.html?id=46149

Their solution was similar to the one taken by Params-Lazy: copy the perl 5.8.8 code under a new function name.  Params-Lazy called that THX_find_runcv with this ifdef:

```
#ifndef find_runcv
/* Perl 5.8.8 */
#define find_runcv(d) THX_find_runcv(aTHX_ d)
/* Taken from pp_ctl.c in 5.8.8 */
CV*
THX_find_runcv(pTHX_ U32 *db_seqp)
{
    PERL_SI      *si;

    if (db_seqp)
        *db_seqp = PL_curcop->cop_seq;
    for (si = PL_curstackinfo; si; si = si->si_prev) {
        I32 ix;
        for (ix = si->si_cxix; ix >= 0; ix--) {
            const PERL_CONTEXT *cx = &(si->si_cxstack[ix]);
            if (CxTYPE(cx) == CXt_SUB || CxTYPE(cx) == CXt_FORMAT) {
                CV * const cv = cx->blk_sub.cv;
                /* skip DB:: code */
                if (db_seqp && PL_debstash && CvSTASH(cv) == PL_debstash) {
                    *db_seqp = cx->blk_oldcop->cop_seq;
                    continue;
                }
                return cv;
            }
            else if (CxTYPE(cx) == CXt_EVAL && !CxTRYBLOCK(cx))
                return PL_compcv;
        }
    }
    return PL_main_cv;
}
#endif /* find_runcv */
```

You could do that too, or use Devel::PPPort, which provides find_recv along with other missing symbols:
http://search.cpan.org/~wolfsage/Devel-PPPort-3.27/PPPort.pm

**Comment by CindyLinz** [comment]
Thank you~ ^^

I've added a commit to do this. However, this module is still not compatible with perl 5.8.8. The syntax structure from perl 5.8.8 is different to perl 5.8.9 or later versions. There're still some works to do.... @@"

**Comment by dsilva** [comment]
Thanks for adding that in.  Are the remaining differences something that could be tackled with #ifdefs?

**Comment by CindyLinz** [comment]
Do you mean to disable some features? But the most basic structures are different... @@"

For the list pattern:

``` perl
[$a,$b]
```

In 5.8.9, the structure is as below:

```
    LISTOP (0xf8dbf0) anonlist 
        OP (0x10e8670) pushmark 
        OP (0xf76ad0) padsv [1] 
        OP (0xf76c30) padsv [2] 
```

In 5.8.8, the structure is as below:

```
    UNOP (0x1d1ee70) srefgen 
        UNOP (0x1d1ef20) null [141] 
            LISTOP (0x1d1f080) anonlist 
                OP (0x1d1f430) pushmark 
                OP (0x1d09ae0) padsv [1] 
                OP (0x1d09c40) padsv [2] 
```

For the hash pattern:

``` perl
{a=>$a,b=>$b}
```

In 5.8.9, the structure is as below:

```
    LISTOP (0xf8d9e0) anonhash 
        OP (0xf8c590) pushmark 
        SVOP (0xf8da90) const  PV (0xf8a620) "a" 
        OP (0xf8c560) padsv [1] 
        SVOP (0xf76d00) const  PV (0xf8a630) "b" 
        OP (0xf8c5c0) padsv [2] 
```

In 5.8.8, the structure is as below:

```
    UNOP (0x1d09b60) srefgen 
        UNOP (0x1d09c00) null [141] 
            LISTOP (0x1d09960) anonhash 
                OP (0x1ee1290) pushmark 
                SVOP (0x1d09d10) const  PV (0x1d1bab0) "a" 
                OP (0x1dd1950) padsv [1] 
                SVOP (0x1d09c70) const  PV (0x1d1bac0) "b" 
                OP (0x1de8590) padsv [2] 
```

mmmmm..... I think I could make it work.. But I need a motive... Do you really need it on 5.8.8? @@"
